GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjY4NDkwOTE2LCJleHAiOjE2Njg0OTA5NzZ9.EGbE1eu6rkK04jIVIbzRjeLKv63trkJ1GHdT2QgSitA

###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjY4NDkwOTA1fQ.PiiUYL5kQQb7QCCvn29NOlKTKxFOMKysGXde9ijFr2Y"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
"username": "Jim"
}